name: Relatório de Bug
description: Reporte um bug para nos ajudar a melhorar.
title: "[Bug]: "
labels: ["bug", "triagem"]
projects: []
assignees:
  - octocat
body:
  - type: markdown
    attributes:
      value: |
        Obrigado por relatar um bug! Por favor, preencha os campos abaixo para nos ajudar a entender o problema.
  - type: input
    id: description
    attributes:
      label: Detalhes do Bug
      description: Forneça uma descrição clara e concisa do bug.
      placeholder: Ex: Botão de login não funciona
    validations:
      required: true
  - type: textarea
    id: what-happened
    attributes:
      label: O que aconteceu?
      description: Também nos diga, o que você esperava que acontecesse?
      placeholder: Diga-nos o que você vê!
      value: "Um bug aconteceu!"
    validations:
      required: true
  - type: dropdown
    id: browser
    attributes:
      label: Navegador
      description: Qual navegador de internet estava usando no momento do Bug?
      options:
        - Chrome
        - Microsoft Edge
        - Firefox
        - Opera
      default: 0
    validations:
      required: true
  
  - type: textarea
    id: logs
    attributes:
      label: Logs relevantes
      description: Cole e cole qualquer saída de log relevante. Isso será formatado automaticamente em código, portanto, não há necessidade de backticks.
      render: shell
  - type: checkboxes
    id: terms
    attributes:
      label: Código de Conduta
      description: Ao enviar este problema, você concorda em seguir nosso [Código de Conduta](https://example.com).
      options:
        - label: Eu concordo em seguir o Código de Conduta deste projeto
          required: true
