name: Reportar Erro
description: Reportar um erro.
title: "[Bug]: "
labels: ["bug", "triage"]
projects: ["1.0", "2.0"]
assignees:
  - bruno
body:
  - type: markdown
    attributes:
      value: |
        Obrigado por reportar um erro! Por favor, preencha o formulário abaixo com o máximo de detalhes possível para nos ajudar a resolver o problema rapidamente.
  - type: input
    id: contact
    attributes:
      label: Detalhes de Contato
      description: Como podemos entrar em contato com você se precisarmos de mais informações?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: textarea
    id: what-happened
    attributes:
      label: O que aconteceu?
      description: Também nos diga, o que você esperava que acontecesse?
      placeholder: Conte-nos o que você vê!
      value: "Um erro ocorreu quando eu tentei..."
    validations:
      required: true
  - type: dropdown
    id: version
    attributes:
      label: Versão
      description: Qual dominio você está usando?
      options:
        - Vercel
        - Kinghost
        - Local
      default: 0
    validations:
      required: true
  - type: dropdown
    id: browsers
    attributes:
      label: Quais navegadores você está vendo o problema?
      multiple: true
      options:
        - Firefox
        - Chrome
        - Microsoft Edge
  - type: textarea
    id: logs
    attributes:
      label: Relevante saídas de log
      description: Por favor, copie e cole qualquer saída de log relevante. Isso será formatado automaticamente em código, então não há necessidade de usar crases.
      render: shell
  - type: checkboxes
    id: terms
    attributes:
      label: Código de Conduta
      description: Ao enviar este problema, você concorda em seguir nosso [Código de Conduta].
      options:
        - label: Eu concordo com os termos do Código de Conduta
          required: true