import type { Pericia } from '../../types';

export const periciasMockData: Pericia[] = [
  {
    id: '00123/2023',
    cliente: 'Empresa de Energia Elétrica S.A.',
    status: 'Fazer Laudo',
    abertura: '2023-10-26',
    autor: 'João da Silva',
    reu: 'Companhia de Seguros Confiança',
    cidade: 'Porto Alegre',
    vara: '10ª Vara Cível',
    descricao: 'Análise de falha em transformador de distribuição que resultou em interrupção de fornecimento para área industrial. A perícia visa determinar a causa raiz da falha, se por defeito de fabricação, manutenção inadequada ou fator externo.',
    valorCausa: 150000.00,
    honorarios: 7500.00,
    pagamentosRecebidos: 3750.00,
  },
  {
    id: '00456/2024',
    cliente: 'Construtora Edificar Ltda.',
    status: 'Concluído',
    abertura: '2024-01-15',
    autor: 'Condomínio Residencial Flores',
    reu: 'Construtora Edificar Ltda.',
    cidade: 'Canoas',
    vara: '3ª Vara Cível',
    descricao: 'Vistoria em instalações elétricas de áreas comuns de condomínio recém-entregue. Verificação de conformidade com o projeto original e com as normas NBR 5410. Laudo concluído e entregue em juízo.',
    valorCausa: 45000.00,
    honorarios: 4000.00,
    pagamentosRecebidos: 4000.00,
  },
  {
    id: '00789/2024',
    cliente: 'Indústria Metalúrgica Pesada S.A.',
    status: 'Aguardando',
    abertura: '2024-03-02',
    autor: 'Pedro Antunes (ex-funcionário)',
    reu: 'Indústria Metalúrgica Pesada S.A.',
    cidade: 'São Leopoldo',
    vara: '2ª Vara do Trabalho',
    descricao: 'Perícia de periculosidade em ambiente industrial. Análise das atividades do reclamante e exposição a riscos elétricos, conforme NR-10 e NR-16. Aguardando agendamento de vistoria técnica no local.',
    valorCausa: 80000.00,
    honorarios: 6200.00,
    pagamentosRecebidos: 0.00,
  },
  {
    id: '01011/2022',
    cliente: 'Shopping Center Metrópole',
    status: 'Arquivado',
    abertura: '2022-08-20',
    autor: 'Lojista A',
    reu: 'Shopping Center Metrópole',
    cidade: 'Porto Alegre',
    vara: '15ª Vara Cível',
    descricao: 'Disputa sobre medição de consumo de energia elétrica em loja do shopping. Perícia concluiu que a medição estava correta. Processo arquivado após acordo entre as partes.',
    valorCausa: 25000.00,
    honorarios: 2500.00,
    pagamentosRecebidos: 2500.00,
  },
  {
    id: '00333/2024',
    cliente: 'Tribunal de Justiça RS',
    status: 'Fazer Honorários',
    abertura: '2024-05-10',
    autor: 'Maria Oliveira',
    reu: 'Banco Nacional S.A.',
    cidade: 'Caxias do Sul',
    vara: '1ª Vara Cível Especializada',
    descricao: 'Análise de equipamentos eletrônicos bancários para verificar alegação de falha de segurança. Laudo técnico inicial foi entregue, aguardando definição e pagamento dos honorários periciais.',
    valorCausa: 250000.00,
    honorarios: 12000.00,
    pagamentosRecebidos: 0.00,
  },
  {
    id: '00555/2023',
    cliente: 'Advocacia Souza & Ramos',
    status: 'Contestação Valor',
    abertura: '2023-11-05',
    autor: 'Fábrica de Calçados Pé-Leve',
    reu: 'Distribuidora de Energia Regional',
    cidade: 'Novo Hamburgo',
    vara: '4ª Vara Cível',
    descricao: 'Quesitos sobre a causa de um incêndio em instalação industrial. O valor dos honorários foi contestado pela parte ré. Aguardando decisão do juiz sobre a impugnação.',
    valorCausa: 500000.00,
    honorarios: 25000.00,
    pagamentosRecebidos: 0.00,
  },
  {
    id: '00678/2024',
    cliente: 'Seguradora Proteção Total',
    status: 'Esclarecimentos',
    abertura: '2024-02-22',
    autor: 'Seguradora Proteção Total',
    reu: 'José Carlos Pereira',
    cidade: 'Pelotas',
    vara: '5ª Vara Cível',
    descricao: 'Análise de sinistro em residência por suposta sobrecarga na rede elétrica. Laudo entregue, e as partes solicitaram esclarecimentos sobre pontos técnicos específicos.',
    valorCausa: 75000.00,
    honorarios: 5500.00,
    pagamentosRecebidos: 5500.00,
  }
];
